apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd

spec:
  project: default

  source:
    repoURL: <place-url-to-forked-repo>
    targetRevision: HEAD
    path: dev
  
  destination: 
    server: https://kubernetes.default.svc
    namespace: myapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true  # self-healing mechanism for resources in the cluster.
      prune: true     # will remove resources that are no longer listed in the configuration